name: Deploy Project
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.1
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Building the project
        run: |
              cd /home/runner/work/accounting/accounting
              echo "export const ENTRYPOINT_LOCAL = 'https://api.nossocep.com.br'" > ./src/config/entrypoint.local.js
              echo "export const DOMAIN_LOCAL = location.host" > ./src/config/domain.local.js              
              yarn
              npm install
              npm update
              npx quasar build
              npx quasar build -m pwa              
      - name: Copy to Nossocep
        uses: horochx/deploy-via-scp@master
        with:
          local: /home/runner/work/accounting/accounting/dist/*
          remote: /var/www/vhosts/nossocep.com.br/sistemas/accounting/dist
          host: 69.162.120.82
          port: 22
          user: nossocep_usu
          key: ${{ secrets.NOSSOCEP }}